### ISSUE TITLE
請洽詢門市或聯絡客服。

### ISSUE THREAD

**Issue by mickey234chu** [zhong1016/feastogether#10]
輸入go run main.go 後會跳這個然後結束程序
想請問是什麼意思?

**Comment by mickey234chu** [comment]
剛剛查一下，好像是取不到token，但我帳號密碼是對的
所以不知道是不是我取的2個cookie有問題，我做法是開editThiscookie看然後copy 到config.ini上修改的
如果我做法不對，哪想請問那2個cookie應該怎麼拿才是正確做法?

**Comment by zhong1016** [comment]
> 剛剛查一下，好像是取不到token，但我帳號密碼是對的 所以不知道是不是我取的2個cookie有問題，我做法是開editThiscookie看然後copy 到config.ini上修改的 如果我做法不對，哪想請問那2個cookie應該怎麼拿才是正確做法?

您好 , 我晚點測試一下

**Comment by mickey234chu** [comment]
感謝!:D

**Comment by zhong1016** [comment]
> 感謝!:D

已更新

**Comment by mickey234chu** [comment]
訂成功了!感謝!:D
