### ISSUE TITLE
03/22 更新api route

### ISSUE THREAD

**Issue by iggh966380** [zhong1016/feastogether#5]
<img width="1440" alt="截圖 2023-03-22 上午11 20 34" src="https://user-images.githubusercontent.com/93663705/226793849-2d577f33-c6ae-4788-8417-309914f02a0c.png">

我這裡推不了新分支XD 直接用截圖的 0322測試正常

**Comment by hykuan** [comment]
你可以 fork 一個發 PR
給你參考 https://gitbook.tw/chapters/github/pull-request

**Comment by zhong1016** [comment]
> <img alt="截圖 2023-03-22 上午11 20 34" width="1440" src="https://user-images.githubusercontent.com/93663705/226793849-2d577f33-c6ae-4788-8417-309914f02a0c.png">
> 
> 我這裡推不了新分支XD 直接用截圖的 0322測試正常

感謝PR , 我剛好也寫完了 XD
晚點在上新的 tag
